services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_llama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

volumes:
  ollama_data:
